name: Create GitHub Releases based on changelog
description: GitHub Action for creating GitHub Releases based on changelog

inputs:
  changelog:
    description: Path to changelog (variables `$tag`, `$version`, `$prefix`, and any string)
    required: false
  title:
    description: Format of title (variables `$tag`, `$version`, `$prefix`, and any string)
    required: false
    default: '$tag'
  draft:
    description: Create a draft release ('true' or 'false')
    required: false
    default: 'false'
  githubref:
    description: Custom GITHUB_REF
    required: true
  branch:
    description: Reject releases from commits not contained in branches that match the specified pattern (regular expression)
    required: false
  prefix:
    description: >
      An optional pattern that matches a prefix for the release tag, before the
      version number.

      If a prefix is provided, an optional '-' character is permitted (but not
      required) between the prefix and the version number.   For example, the
      tags 'my-crate-v0.1.2' and 'my-crate0.1.0' both have the prefix 'my-crate'.

      This is interpreted as a bash-style regular expression, so it may be used
      to match multiple prefix strings. Therefore, literal characters that
      are part of bash's regular expression syntax, such as `$`, `^`, `[`, `]`,
      `{`, `}`, `(`, `)`, and `|` must be escaped if they occur in the prefix
      pattern.

      If a prefix pattern is provided, the portion of the tag that matched the
      prefix can be interpolated into `title` and `changelog` via the `$prefix`
      variable.
    required: false
    default: ''

outputs:
  computed-prefix:
    description: >
      The computed prefix, including '-' and 'v' if found.
  version:
    description:
      The version number extracted from the tag. The tag name is a concatenation of computed-prefix
      and version.
runs:
  using: node16
  main: main.js
