name: Create GitHub Releases based on changelog
description: GitHub Action for creating GitHub Releases based on changelog

inputs:
  changelog:
    description: Path to changelog
    required: false
  title:
    description: Format of title (variables `$tag`, `$version`, and any string)
    required: false
    default: '$tag'
  draft:
    description: Create a draft release ('true' or 'false')
    required: false
    default: 'false'
  branch:
    description: Reject releases from commits not contained in branches that match the specified pattern (regular expression)
    required: false

runs:
  using: node12
  main: main.js
