name: Release

permissions:
  # TODO: once `releases: write` is supported, use it instead.
  contents: write

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.*

defaults:
  run:
    shell: bash

jobs:
  create-release:
    if: github.repository_owner == 'taiki-e'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          title: $version
          branch: 'main|v[0-9]+'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
